"""Add created_at and updated_at to tags and tag_categories

Revision ID: 7f85fe8a5753
Revises: 08e56e4e95cd
Create Date: 2025-05-13 03:09:43.854185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f85fe8a5753'
down_revision = '08e56e4e95cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag_categories', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('tag_categories', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('tags', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('tags', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'updated_at')
    op.drop_column('tags', 'created_at')
    op.drop_column('tag_categories', 'updated_at')
    op.drop_column('tag_categories', 'created_at')
    # ### end Alembic commands ### 